services:
  mongodb:
    image: mongo:7
    container_name: dispatchx-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    container_name: dispatchx-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: dispatchx-rabbitmq
    ports:
      - "5672:5672" # AMQP protocol — your Node app connects here
      - "15672:15672" # Management UI — you'll open this in a browser
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  mongo-data:
  redis-data:
  rabbitmq-data:
